version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: warehouse-productivity-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: warehouse_productivity
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse-productivity-api
    depends_on:
      - mysql
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://user:password@mysql:3306/warehouse_productivity
      - JWT_ACCESS_SECRET=dev-access-secret
      - JWT_REFRESH_SECRET=dev-refresh-secret
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mysql_data: 